apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-api-deployment
  labels:
    app: common-api
  namespace: cp-dev-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: common-api
  template:
    metadata:
      labels:
        app: common-api
    spec:
      containers:
      - name: common-api
        image: $REGISTRY_HARBOR_URL/container-platform-new-dev/container-platform-common-api:$BUILD_NUMBER
        imagePullPolicy: Always
        ports:
        - containerPort: 2334
        env:     
        - name: HAPROXY_IP
          value: HAPROXY_IP
        - name: CONTAINER_PLATFORM_API_URL
          value: CONTAINER_PLATFORM_API_URL
        - name: MARIADB_USER_ID
          value: MARIADB_USER_ID
        - name: MARIADB_USER_PASSWORD
          value: MARIADB_USER_PASSWORD
      imagePullSecrets:
        - name: cp-dev-secret
---
apiVersion: v1
kind: Service
metadata:
  name: common-api-deployment
  labels:
    app: common-api
  namespace: cp-dev-namespace
spec:
  ports:
  - nodePort: 32700
    port: 2334
    protocol: TCP
    targetPort: 2334
  selector:
    app: common-api
  type: NodePort